config/routes.rb
StoicPenknife::Application.routes.draw do
  devise_for :mailers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'my_devise/registrations' }

  resources :rehearsals
  resources :exercises
  resources :quotations
  resources :doctrines

  get 'index' => 'welcome#index'
  get 'about' => 'welcome#about'
  get 'how_it_works' => 'welcome#how_it_works'
  get 'contact' => 'welcome#contact'
  get 'doctrines_index' => 'doctrines#index'
  get 'doctrines_new' => 'doctrines#new'
  get 'doctrines_introduction' => 'doctrines#introduction'
  get 'doctrines_assent' => 'doctrines#assent'
  get 'doctrines_desire' => 'doctrines#desire'
  get 'doctrines_action' => 'doctrines#action'
  get 'doctrines_disciplines_intro' => 'doctrines#disciplines_intro'
  get 'doctrines_dogmas_intro' => 'doctrines#dogmas_intro'
  get 'users' => 'users#index'
  get 'tags/:tag', to: 'tags#index', as: :tag
  root 'welcome#index'

end

app/models/rehearsal.rb
class Rehearsal < ActiveRecord::Base
  belongs_to :exercise
  belongs_to :user
  has_many :questions, through: :exercises
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers
  accepts_nested_attributes_for :questions
end

app/controllers/rehearsals_controller.rb
class RehearsalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_rehearsal, only: %i[show edit update destroy]
  before_action :fetch_city, only: %i[new]

  # Load CanCan roles for Controller
  load_and_authorize_resource

  # GET /rehearsals
  def index
    @rehearsals = Rehearsal.where(user_id: current_user.id)
  end

  # GET /rehearsals/1
  def show
    @exercise = @rehearsal.exercise
  end

  # GET /rehearsals/new
  def new
    @exercise = Exercise.find(params[:exercise])
    @rehearsal = @exercise.rehearsals.new
    questions = @rehearsal.exercise.questions
    questions.each do |question|
      @rehearsal.answers.build(question_id: question.id)
    end

    exercise_tags = @exercise.tags
    @published_quotations = Quotation.where(publish: true)
                                     .find_me_with(exercise_tags)
  end

  # GET /rehearsals/1/edit
  def edit
    @exercise = @rehearsal.exercise
  end

  # POST /rehearsals
  def create
    @rehearsal = Rehearsal.new(rehearsal_params)
    @rehearsal.user_id = current_user.id
    respond_to do |format|
      if @rehearsal.save
        format.html do
          redirect_to @rehearsal.exercise,
                      notice: "You just practiced #{@rehearsal.exercise.title}.
                      Great job."
        end
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /rehearsals/1
  def update
    if @rehearsal.update(rehearsal_params)
      redirect_to @rehearsal.exercise,
                  notice: "You just updated your earlier
                  practice of #{@rehearsal.exercise.title}."
    else
      render action: 'edit'
    end
  end

  # DELETE /rehearsals/1
  def destroy
    @rehearsal.destroy
    respond_to do |format|
      format.html { redirect_to @rehearsal.exercise }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_rehearsal
    @rehearsal = Rehearsal.find(params[:id])
  end

  def fetch_city
    @rehearsal_location = request.location.city unless request.location.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def rehearsal_params
    params.require(:rehearsal).permit(:tally,
                                      :exercise_id,
                                      :city,
                                      answers_attributes: %i[
                                        id
                                        reply
                                        question_id
                                        _destroy
                                      ])
  end
end

app/helpers/rehearsals_helper.rb
module RehearsalsHelper
end

app/views/rehearsals/_answer_fields.html.haml
%p
  = f.label :reply, "Answer"
  = f.text_area :reply
  = f.check_box :_destroy
  = f.label :_destroy, "Remove"

app/views/rehearsals/_e_answer_fields.html.haml
%p
  = f.label :reply, "Answer"
  = f.text_area :reply
  = f.check_box :_destroy
  = f.label :_destroy, "Remove"

app/views/rehearsals/_form.html.haml
= bootstrap_form_for @rehearsal do |f|
  = f.hidden_field :user_id
  .form-group.col-md-12.mb-2
    %p= @exercise.general_description
    - @rehearsal.answers.each_with_index do |answer, index|
      .form
        .form-group
          #questions
            = f.fields_for :answers, answer do |builder|
              = builder.text_area :reply, label: "#{answer.question.inquiry}", class: "form-control", id: "form-border", rows: 2
              = hidden_field_tag "rehearsal[answers_attributes]#{index}[question_id]", answer.question.id

            = hidden_field_tag 'rehearsal[exercise_id]', @rehearsal.exercise.id
            = hidden_field_tag 'rehearsal[city]', @rehearsal_location
    - if @rehearsal.answers.count == 0
      = render 'progress_bar'

    .actions
      = f.submit "Finish My Practice of #{@exercise.title}", class: "btn btn-md btn-primary mt-3"

app/views/rehearsals/_progress_bar.haml
.progress
  .progress-bar.bg-success{style: "min-width: 5px;"}
/ JQuery progress bar script
:javascript
  $(".form").one('change',function () {
      var number_of_questions = $(".form").length
      var width = ((1 / number_of_questions) * 100);
  
      var filled = $(".progress-bar").data( "filled" ) || 0;
      $(".progress-bar").data( "filled", ++filled );
  
      $(".progress-bar").css( "width", (width * filled) +"%" );
  });

app/views/rehearsals/edit.html.haml
.container
  .row
    .col-md-8
      .card.bg-dark
        .card-header
          %h3
            Edit rehearsal of
            = "#{@exercise.title}"
            %br
            on
            = "#{@rehearsal.created_at.strftime("%B %d, %Y at %H:%M")}"
        .card-body
          = render 'form'
          %h4
            Originally rehearsed in/on:
            %p= @rehearsal.city
            %p= @rehearsal.created_at.strftime("%B %d, %Y at %H:%M")

          = link_to "Back to #{@exercise.title} exercise page", @rehearsal.exercise, class: "btn btn-sm btn-danger mb-3"
          = link_to 'Delete This Rehearsal', @rehearsal, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-sm btn-danger"

app/views/rehearsals/index.html.haml
%h1 Listing rehearsals&nbsp;#{link_to 'Rehearse a new exercise', exercises_path}

%table
  %tr
    %th Exercise
    %th Description
    %th Category

  - @rehearsals.each do |rehearsal|
    %tr
      %td= rehearsal.exercise.title
      %td= rehearsal.exercise.general_description
      %td= rehearsal.created_at.strftime("%B %d, %Y, at %H:%M")
      %td= link_to 'Show', rehearsal
      %td= link_to 'Edit', edit_rehearsal_path(rehearsal)
      %td= link_to 'Destroy', rehearsal, :method => :delete, :data => { :confirm => 'Are you sure?' }
    - rehearsal.exercise.questions.each do |question|
      %tr
        %td Question:&nbsp;
        %td= question.inquiry
      - question.answers.each do |answer|
        %tr
          %td Answer:&nbsp;
          %td= answer.reply

%br

app/views/rehearsals/new.html.haml
.container
  .row
    .col-md-8
      .card.mb-3.bg-dark
        .card-body
          .card-title.ml-3
            %h4
              Practice
              = @exercise.title
          = render 'form'
          = link_to "Back to the exercise page", @exercise, class: "btn btn-sm btn-info ml-3"
    .col-3
      - unless @published_quotations.nil? || @published_quotations.empty?
        .card.bg-warning
          .card-body
            %b Ancient Philosopher Who Practiced This Exercise
            - @published_quotations.each do |quotation|
              - unless @exercise.tags.empty?
                %br
                .col
                  .row
                    %br
                    .card-text
                      = link_to @exercise.tags.first.name, tag_path(@exercise.tags.first.name), class: "small text-muted"
              .card-text
                = quotation.passage + "\""

app/views/rehearsals/show.html.haml
.container
  .row
    .col-md-8.col-sm-offset-1
      .card.bg-dark
        .card-header
          %h3
            My Practice of
            = "#{@exercise.title}"
            %h5
              Originally practiced in
              %b 
                -if @rehearsal.city?
                  = @rehearsal.city
                -else
                  Unknown City
              on
              %b
                = "#{@rehearsal.created_at.strftime("%B %d, %Y at %H:%M")}"
        .card-body
          .card-title
            %h5 Exercise Overview
            %p= @exercise.general_description
          .card-text
            - @rehearsal.answers.each_with_index do |answer, index|
              %table.table.table-light
                %tr
                  %h5
                    %th
                      %b= answer.question.inquiry
              %p
              %tr
                %p
                  %td= answer.reply
          = link_to "Back To #{@exercise.title}", @rehearsal.exercise, class: "btn btn-sm btn-secondary mb-3"
          = link_to 'Edit This Rehearsal', edit_rehearsal_path(@rehearsal), class: "btn btn-sm btn-secondary mb-3"