config/routes.rb
StoicPenknife::Application.routes.draw do
  devise_for :mailers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'my_devise/registrations' }

  resources :rehearsals
  resources :exercises
  resources :quotations
  resources :doctrines

  get 'index' => 'welcome#index'
  get 'about' => 'welcome#about'
  get 'how_it_works' => 'welcome#how_it_works'
  get 'contact' => 'welcome#contact'
  get 'doctrines_index' => 'doctrines#index'
  get 'doctrines_new' => 'doctrines#new'
  get 'doctrines_introduction' => 'doctrines#introduction'
  get 'doctrines_assent' => 'doctrines#assent'
  get 'doctrines_desire' => 'doctrines#desire'
  get 'doctrines_action' => 'doctrines#action'
  get 'doctrines_disciplines_intro' => 'doctrines#disciplines_intro'
  get 'doctrines_dogmas_intro' => 'doctrines#dogmas_intro'
  get 'users' => 'users#index'
  get 'tags/:tag', to: 'tags#index', as: :tag
  root 'welcome#index'

end

app/models/doctrine.rb
class Doctrine < ActiveRecord::Base
  include Taggable

  has_many :taggings, as: :tagable
  has_many :tags, through: :taggings
end

app/controllers/doctrines_controller.rb
class DoctrinesController < ApplicationController
  # Load CanCan roles for Controller
  load_and_authorize_resource only: %i[new create]

  def index
    @doctrines = Doctrine.all
  end

  def new
    @doctrine = Doctrine.new
  end

  def create
    @doctrine = Doctrine.new(doctrine_params)
    @doctrine.save
    redirect_to doctrines_new_path
  end

  def show
  end

  def doctrine_params
    params.require(:doctrine).permit(:file_name, :tag_list, :publish)
  end
end

app/helpers/doctrines_helper.rb
module DoctrinesHelper
end

app/views/doctrines/action.html.haml
%center
.container
  .row
    .col-md-8
      #accordion.panel-group
        .panel
          .panel-heading.stoic-brown
            %h4.panel-title
              Discipline of Action
          .panel-body.stoic-dark-text
            %p Each of the three disciplines - assent, desire and action, concerns itself with a realm of knowledge or 'science'. The Discipline of Assent is associated with the science of logic. Logic is the tool we use to interrogate our impressions about the world and to formulate correct ones. The Discipline of Desire is associated with Physics, since Physics is an exploration of the laws of Nature - laws which dictate behavior in the world around us that occurs independent of our will and control. The ancient Stoic philosophers associated the Discipline of Action with Ethics - the science - in Greek <i>epistime</i> - of how to act and interact with the world, and Virtue, which Stoic philosophers defined as the <i>techne</i> or knowlege of the correct way to live.
            %p The French historian of philosophy Pierre Hadot describes the Discipline of Action as "all the acts and movements which respond to the requirements of integral human nature... the faculty of growth, of sensation, and of reason." Hadot argues persuasively that the chief ethical cause for the Stoic Marcus Aurelius, for example, is serving the invisible city of reasoning beings that make up the world. This is defined as the virtue of <i>dikaisoyne</i> or 'justice'. %p The following passage from Marcus Aurelius highlights his goal, "Impassivity (ataraxia) with regard to the events, [Discipline of Desire] brought about by the exterior cause. Justice (dikaiosyne) in the actions brought about by the cause that is within you. In other words, let your impulse to act and your action have as their goal the service of the human community, because that, for you, is in conformity with your nature" (IX, 31).
            %p Justice is one of four classical virtues (again, knowledge about the correct way to live and act, thus at the heart of the Discipline of Action) found already in Plato and later alive in the Stoic tradition. The other threecardinal virtues are <i>sophia (wisdom/truth)</i>, <i>agothos</i> (strength/courage) and <i>eusebes</i> (piety/temperance).
            %p Stoic written exercises associated with action tend to look like the Marcus Aurelius passage cited above. The exercise reminds the practicioner of the virtue of justice, the importance of acting for the good of the human community. Other times, Discipline of Action exercises trigger reflections on all four virtues. For example, Marcus Aurelius writes, "And how is he [man] to do this [live correctly]? By having principles to govern his impulses and actions. What are these principles? Those of good and evil - the belief that nothing is good for a human being which does not make him just, self-controlled, brave, and free: and nothing evil which does not make him the opposite of those." (VIII, 1).
            %p All three disciplines are ultimately connected. By reflecting on our impressions and logic, we can more clearly determine how we ought to act. Explains Hadot, "The discipline of action, like the other disciplines in the domains in which they are exercised, will therefore begin by imposing the norms of reason and reflection upon human activity." Hadot cites Marcus' Meditation from Book XII, 20: "In the first place, nothing at random, and nothing that is not related to some goal. Second: do not relate your actions to anything other than a goal which may serve the human community." Hadot concludes, "The vice which is opposed to the discipline of action is thus frivolity (<i>eikaiotes</i>). It is the opposite to that seriousness or gravity with which all human actions should be accomplished. This human frivolity or lack of reflection does not know how to submit to the discipline of action; it is the agitation of a jumping jack, a puppet or a top."
            %p#big What about when stuff goes wrong?
            %p The Stoics recognize that our actions will not always lead to the outcomes that we hope for. On the one hand - and many Stoic Penknife exercises deal with this question - the challenge afforded by failures, setbacks, disappointments, surprises, is an opportunity for growth. On other hand, they are an opportunity to practice the Discipline of Desire. Writes Hadot, "The Stoics do not only say, 'I don't know whether my action will succeed.' Rather, they also say, 'Since I don't know in advance what the results of my actions will be, and what Destiny has in store for me, I have to make such-and-such a decision in accordance with probability and rational estimate, without any absolute certainty that I am making the right choice or doing the right thing." He later, once again, quotes Marcus Aurelius, who writes, "People can perfectly well prevent me from carrying out such-and-such an action. Thanks, however to action 'with a reserve clause' and to 'turning obstacles upside down', there can be no obstacle to my intention, nor to my disposition. For my thought can 'turn upside down' everything that presents an obstacle to my action, and transform the obstacle into an object toward which my impulse to act ought preferably to tend. That which impeded action thus becomes profitable to action, and that which blocked the road allows me to advance along the road" (V, 20, 2).

app/views/doctrines/assent.html.haml
%center
.container
  .row
    .col-md-8
      %h4
        Theory of Representation, Judgement and Assent
      %p This short resumée of the late stoic theory on representation, judgement and assent, give the basic knowledges to understand the Discipline of Assent.
      %b Representation
      %p The stoics understood sensorial perception as a corporal process common to lot of animals, by which the image of an external object is transmitted to the soul / to the mind.
      %p This image, called in greek "phantasia" (like "phantasy"), is produced in the soul and more specifically in the "directive principle": in greek the "eghemonikón" (like "egemonic" - something ruling on everything else).
      This "phantasia" ...
      %ol
        %li it takes the place of the represented object and pretend to be the object itself. We look at a table and make a picture of it, when we think about this picture, we will mean that we're thinking about the table, not about the picture of the table. If it can seem like a subtle and pedantic difference, it is instead quite important and the exact nature of this process will stay in the middle of millennial philosophical discussions.
        %li it produce a perturbation in the soul / in the mind. Our mind reacts to representation depending on the relation between their represented contents and other structures of the mind itself. How different features of a representation can perturb the mind, will be discussed in few lines.
      %b Judgement
      %p If the representation is formed depending on hard to change structure of the mind, which lay out of control of the conscious mind, judgements are sentences or bundles of sentences enunciating the nature, quality and value of the represented object.
      %p For example if I see a cake, the representation of the cake will be produced in my mind and I have no power on it: I can't choose to imagine it or not. The cake will appear in my mind with certain features and among them the actual existence of the cake with its position in space: in front of me.
      %p This representation take the place of the object and already perturbates my mind, i.e. elicits mental processes of various kind.
      Some mind processes, more active and changeable as the mere perception, will actually "say" things about this cake, for example:
      %ul
        %li it will taste good (info coming from past memories)
        %li it is not mine
        %li it is bad for my body figure
        %li I'll feel good eating it
        %li I'll feel bad after eating it
        %li etc.
      This are judgements regarding the cake. They came in large part spontaneously and depend on our previous experiences of representation, judgement and reflection.
      %p That means NOT that judgements are under our control, the opposite is true: our judgements depend on the structure and actual state of our mind. That means: it depends on a story of development, interaction, socialization, pain and pleasure, joy and sadness, punishments and praise, etc.
      %b Assent
      %p In the end we come to what is really in our power: the assent to representations and judgements.
      %p If before reacting to our first representations and judgements we find the time to look at them one more time, there we find a narrow but decisive space for freedom: the moment of assent.
      %p Every representation or judgement, which became conscious, can be scrutinized again and be assented to or rejected:
      %ul
        %li assent - "ok, this representation is adequate" or "I really agree on this judgement!"
        %li rejection - "this representation is an illusion" or "This judgement is in contrast with my deepest principles and believes, I don't agree with it!"
      Aulus Gellius (c. 125 – after 180 AD) tells us (in his Noctes Atticae) about this bundle of passive and active moments, describing the reaction of a philosopher to a thunderclap. Here my personal paraphrases:
      %p The things "throw themselves" on us to be perceived, "stamp" our mind and produce an emotion in the soul. This process does not depend on our will.
      %p The assent to this perceptions and to the judgements which follow as reaction, this assent instead is a free act of the human mind.
      %p The wise man jumps and turns pale as a thunderclap break the air and hits his ears. In this regard he acts exactly as any other human being, BUT he does not assent to the judgements which follow: "this thing is dreadful and dangerous" or "the gods are upset with me". The fool instead give his assent to the first representations and judgements that come to mind.
      %p Resuming these elements one more time:
      %ol
        %li Representation (phantasia): the stamp of the thunderclap in our mind (perception) and effect of it ("jump" because of instinctive reaction to explosive and loud sound)
        %li Judgement (hypolépsis): an inner discourse like enunciating feature of the represented object ("it is dangerous")
        %li Assent (synkatathesis): the acceptance of this representations and judgements as adequate or the dismissal of them as false or nonsensical
      %b Adequate Representation
      %p Instead of starting a complex theoretical discussion on the possibilities and forms of knowledge [note to deepen this subject] let's read two passages about adequate representations respectively from Epictetus and Marcus Aurelius:
      %ul
        %li "For as Socrates said, "we ought not to live a life without examination," so we ought not to accept an appearance without examination, but we should say, "Wait, let me see what you are and whence you come"; like the watch at night, "Show me the pass." "Have you the signal from nature which the appearance that may be accepted ought to have?"."
        Epictetus, Discourses: III, 12, 15
        %li "Say nothing more to thyself than what the first appearances report. Suppose that it has been reported to thee that a certain person speaks ill of thee. This has been reported; but that thou hast been injured, that has not been reported. I see that my child is sick. I do see; but that he is in danger, I do not see. Thus then always abide by the first appearances, and add nothing thyself from within, and then nothing happens to thee. Or rather add something, like a man who knows everything that happens in the world."
        MA, VIII, 49
      From these two quotes it is evident what makes a representation "not-adequate": certain additions and deformations, which do not correspond to the nature of the observed object.
      %p An adequate representation does not add interpretation to the pure perception of the object, while a not adequate one substitute to the pure perception an image of something different.
      %p For example: If I see a guy with a hat, striped shirt, disfigured face and a glove armed with razors... I have three main options:
      %ol
        %li Assume I've seen this guy and stop my representation there;
        %li Assume I've seen Freddy Kruger;
        %li Assume it's a camouflage and that it must be Carnival or Halloween.
      Which one of this representations would be adequate? A "totally adequate" representation is impossible for a human being, so we have to ask which one is "more adequate", and the answer is: the first one!
      %p To guess that it's Freddy Kruger or a camouflage implies some additional consideration and inferences, that means: it does not belong to the representation of what we have seen.
      %p For sure: we can't and we don't want always have to make this distinction, because it would enormously complicate our reasoning and just make our everyday life impossible!
      %p Take the example from Marcus Aurelius to understand when and how this distinction can actually help us:
      %p "... Suppose that it has been reported to thee that a certain person speaks ill of thee. This has been reported; but that thou hast been injured, that has not been reported. ..."
      %p In this case to stop the flow of thoughts and to come back to the first representation can really change the course of the further developments.
      %p I have inconsciously translated the fact that someone said that I'm a moron... with the fact that "I have been damaged" or even that "that person damaged me" or that "she did something wrong to me".
      %p Here to "stop" the representation allows us to notice that it is saying "to much" and than ask which are the "first data" and which features have been added.
      %p In the example the data are: a person said that I am a moron.
      %p To jump to the conclusion of have being damaged, I should first analyse which relation occurs between the utterance of this opinion and something belonging to be having been broken or destroyed.
      %p To assume that she did "something wrong" would imply a moral judgement about right and wrong, that means I should find some rules for it. Etcetera...
      %p
      %b Adequate Judgement
      %p This informations, which we said a representation should not have, can be parts of a judgement, i.e. of a sentence enunciating something about one or more objects and their relationships.
      %p I can for example affirm that Maria damaged me by affirming that I am a moron in front of Sabrina, because it reduces the chances I had to seduce her. This judgement implies other perceptions and judgements and can therefore be defined as adequate or not only on the basis of a larger analysis of my beliefs and other judgements.
      %p To take care of my own beliefs and judgements is not easy work, because it requires to track down their genesis back to the origins or build new chains of judgements basing on "general principles" I have recognised or established.
      %p To fulfil this difficult task constitute the main function of the Discipline of Assent: analysis and selection of beliefs, judgements and dogmas (general principles).
      %p Epictetus means that there are some "pre-notions", common to every human being and necessarily true for everyone, which are the basis of every further judgement. To apply this pre-notions (for example, that the good is to prefer) correctly to the actual judgement of a specific situation or object is instead very different from human to human and it is the task of philosophical education to make one capable to apply them right.

app/views/doctrines/desire.html.haml
%center
.container
  .row
    .col-md-8
      #accordion.panel-group
        .panel
          .panel-heading.stoic-brown
            %h4.panel-title
              Discipline of Desire
          .panel-body.stoic-dark-text
            %p A key argument of the Stoic philosophers is to separate what is in our control and what is outside of our control. The thoughts of other people, for example, are outside of our control. Our words that we choose - which may, of course, influence those thoughts, are inside our control. To focus, for example, on the thoughts of others is to weaken our reasoning power; to focus instead, on our own persuasive abilities is to strengthen our power.
            %p Pierre Hadot, the French historian of philosophy, calls this "discipline" or practice of sorting out what is in and outside of our power the "Discipline of Desire." Desire, in this sense, means our passions - the passive elements of our lived experience, in which forces external to our consciousness incite, press upon and move us - hence making us passive before them. The active part of our life flows from our consciousness. 
            %p Hadot cites many examples in his book <u>The Inner Citadel</u> of Marcus Aurelius practicing the Discipline of Desire. Marcus Aurelius writes, for example, "He who separates and distances himself from the Reason of common Nature, and complains about what happens to him, is an abscess upon the world..." (IV, 29, 2). Marcus argues that, once we separate what is in and outside of our control, it is irrational to complain about that which is outside. 
            %p The discipline of recognizing this separation frees us to dedicate our power to those elements which are in our control: our thoughts about the world, which in turn shape our words, our actions and our characters. We all know people who waste their power on complaining about the world around them. (We all know that we, too, often act this way). Marcus Aurelius describes this freedom, "You will open up a vast field for yourself as you embrace the totality of the cosmos in your thought, conceive everlasting eternity, and consider the rapid metamorphosis of each individual thing." (IX, 32). 
            %p Part of this freedom stems, ironically, from recognizing how little is actually within our control. Marcus Aurelius frequently writes about the vast amount of the universe which is operating completely independently of us. He writes about our small part of time, matter, soul and patch of earth that we inhabit and control. "What a tiny part of the infinite time is assigned to each one of us! For it disappears so quickly into the everlasting. What a tiny portion of universal substance, what a tiny part of the universal soul! On how tiny a part of the entire earth do you crawl!" (XII, 32). Elsewhere he writes, "Asia and Europe are corners of the world. The sea is a drop of the world. Athos is a lump of earth, and all present time is a point within infinity. Everything is tiny and unstable, and everything vanishes (in immensity)" (VI, 36). We waste energy thinking of many outside-of-our-control experiences as big, terrible and dramatic. By recognizing, through a kind of hyerbole, how tiny our vexations are, how much lies outside of our control, we ironically free more of our internal resources for those elements which we do control.
            %p The Stoic Discipline of Desire goes even further. The Stoics ask the question, what is the wise attitude toward these elements outside of our control? Their answer is, in a sense, love. Since all these events are outside our control, the wise response is to love them as the gifts of Nature. Any other response to events outside our control is irrational and counterproductive: inducing passions - passions which weaken our active powers and make us more passive. Hadot draws inspiration from a Nietzschian phrase to entitle this capacity <i>Amor Fati</i> or, the Love of Fate. He summarizes the outcome of this ancient discipline: "The result of the discipline of desire... was to bring people inner serenity and peace of mind, since it consisted in the joyful consent to everything that happens to us through the agency of universal Nature and Reason. Amor Fati, or the love of fate, thus led us to want that which the cosmos wants, to want what happens, and to want what happens to us" (<i>The Inner Citadel</i>, Chapter 8, "The Discipline of Action, or Action in the Service of Mankind"). 

app/views/doctrines/disciplines_intro.html.haml
%center

.container
  .row
    .col-md-8
      #accordion.panel-group
        .panel.panel-danger
          .panel-heading
            %h4.panel-title
              An Overview and Introduction to the Stoic Disciplines
          .panel-body
            = link_to 'Ethics', tag_path(:Ethics), class: "btn btn-default"
            One way of seeing it, is that the three Disciplines structure the relationship of human Reason with three objects of our experience and reflection:
            %ol
              %li the universal Nature,
              %li the human Reason itself,
              %li my action in the world.
            Let's imagine a human Reason appearing all of the sudden in the middle of existence, what are the most basic questions it would ask?
            %ol
              %li "what the heck is that?"
              The focus is on the "outside world" and the goal is to understand how it works and from which rules is governed.
              %li "who is thinking and how is that happening?"
              The focus is on the thinking subject now, trying to understand its own rules and way of functioning.
              %li "what should I do?"
              It's time to ask ethical questions: What is worth to be pursued? What am I part of? What can I care for? That means to bring our attention to the other individuals out there and ask ourselves what kind of relationship we have with them.
            Marcus Aurelius VIII, 27 "There are three relations between thee and other things: the one to the body which surrounds thee; the second to the divine cause from which all things come to all; and the third to those who live with thee. "
            %p Also philosophy as intellectual inquiry was divided in three sections in late stoic schools: physic, logic and ethics. Even if philosophy is a unitary practice, the ancient stoics divided its questions under three mains questions, corresponding to the three disciplines:
            %ul
              %li Physics: questions about the universal Nature and its laws
              %li Logic: questions about the human Reason and its laws
              %li Ethics: questions about the right attitude towards others
            The differentiation of philosophical practice in three Disciplines helps orientating and structuring the exercises, BUT we have to understand it as a analytical differentiation and not a substantial one. If we try to track down a single Discipline, we'll notice that they are totally interrelated, to the point that practising a Discipline implies volens nolens the practising the other two also.
            %p We will maintain this differentiation because it enable us to describe the inner paths of stoic philosophical practice.
            %b Following: schematic resumées of the three Disciplines
            %p It will not be totally clear and understandable at the beginning, just read it through asking yourself: what could that mean? Formulate hypothesis, ready to change them as far as you start reading the chapters on the single disciplines.
            %p The capital letter before the name of the Discipline is the one we'll use to tag the disciplines in the analysis of Marcus Aurelius Meditations, so: remember that! ;)
            %b [A] Discipline of Assent
            %ul
              %li Correspond to the "logic" in the threefold partition of philosophy
              %li The object of this discipline is the assent to judgements and representations
              %li It regards the things, which are exclusively in our own power
              %li It regard the relationship of the Reason with: itself
              %li Consists in: selective assent to judgements and representations. It implies review, inspection, examination, and eventually revisions of our beliefs and judgements.
              %li Attitude: free in own domain, joy in the inner Citadel
              %li Effect: freed us from false believes, contradictory judgements, restores and develop the power of the mind, protect the boundaries of the inner Citadel and offer protection and recover in troubled times
              %li Closest related dogmas: freedom of assent, distinction between goods and indifferents
              %li Relation to the other two disciplines: every discipline founds on judgements and representations, therefore every other discipline relays on the discipline of assent for the selection of its basic elements
            %b [D] Discipline of Desire
            %ul
              %li Correspond to "physics" in the threefold partition of philosophy
              %li The object of this discipline the universal Nature and the indifferents
              %li It regards the things, which are not in our own power
              %li It regards the relationship of the Reason with: the eternal and relentless flow of the Cosmos
              %li Consists in:
              %ol
                %li situate every happening it the perspective of the whole Cosmos,
                %li refuse to desire that anything happens different from how the universal Nature has ordered,
                %li assent with joy to the laws of universal Nature
              %li Attitude: "familiarity" [note] with nature, recognition of self as part of the universal nature, thankfulness for the existence of the Cosmos
              %li Effect: freed the stoic from the delusional desire which contradict the necessary reality and reconnect her intellect with the cosmos (the divine intellect, or Zeus)
              %li Closest related dogmas: Providence, rationality of the universe, difference between the thing in our power and those not in our power, principle of sufficient reason, determinism, monism
              %li Relation to the other two disciplines: it helps the discipline of assent to build and defend the boundaries to the "inner Citadel". It equips the discipline of Impulse with appropriate models of the outer world and permits a more precise formulation of the "Clause of Reserve".
            %b [I] Discipline of Impulse to Action
            %ul
              %li Correspond to "ethics" in the threefold partition of philosophy
              %li The object of this discipline is the human Nature and how it relates to others [in it: il modo in cui la nostra causalità si inserisce nella causalità del mondo]
              %li It regards the things we have to take care of or commit to
              %li It regards the relationship of the Reason with: the nature of the human being and the communities it is intrinsically part of
              %li Consists in: 1. act "with Reserve", for the good of the Whole, never without a good reason/goal
              %li Attitude: the will to act following our own nature
              %li Effect: equip the stoic with criteria to distinguish and choose between the indifferents and prepare her to select the indifferents without losing her calm and freedom
              %li Closest related dogmas: the natures and polis of the human being; the community of rational being;
              %li Relation to the other two disciplines: it helps by the choice of adequate activities, tasks and duties and the determination of the resources to devote them. Between them is also to place Philosophy and the practice of philosophical exercises, therefore is this discipline determinant for the actual place of Philosophy in our life.

app/views/doctrines/dogmas_intro.html.haml
%center

.container
  .row
    .col-md-8
      #accordion.panel-group
        .panel.panel-danger
          .panel-heading
            %h4.panel-title
              An Overview and Introduction to the Stoic Dogmas
          .panel-body

app/views/doctrines/new.html.haml
%h1 New Doctrine Tag

= link_to 'Back', doctrines_index_path

= form_for @doctrine do |f|
  - if @doctrine.errors.any?
    #error_explanation
      %h2= "#{pluralize(@quotation.errors.count, "error")} prohibited this quotation from being saved:"
      %ul
        - @doctrine.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :doctrine_file_name
    = f.text_field :file_name
  .field
    = f.label :tag_list, "Category Tags"
    %br
    = f.label :tag_list, "(Separated by commas,"
    %br
    = f.label :tag_list, "e.g. Assent, Sex, Freedom)"
    = f.text_area :tag_list, class: "form-control", rows: "4"
  .field
    = f.check_box :publish
    = f.label :publish_to_exercise_page
  .actions
    = f.submit 'Save'