config/routes.rb
StoicPenknife::Application.routes.draw do
  devise_for :mailers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'my_devise/registrations' }

  resources :rehearsals
  resources :exercises
  resources :quotations
  resources :doctrines

  get 'index' => 'welcome#index'
  get 'about' => 'welcome#about'
  get 'how_it_works' => 'welcome#how_it_works'
  get 'contact' => 'welcome#contact'
  get 'doctrines_index' => 'doctrines#index'
  get 'doctrines_new' => 'doctrines#new'
  get 'doctrines_introduction' => 'doctrines#introduction'
  get 'doctrines_assent' => 'doctrines#assent'
  get 'doctrines_desire' => 'doctrines#desire'
  get 'doctrines_action' => 'doctrines#action'
  get 'doctrines_disciplines_intro' => 'doctrines#disciplines_intro'
  get 'doctrines_dogmas_intro' => 'doctrines#dogmas_intro'
  get 'users' => 'users#index'
  get 'tags/:tag', to: 'tags#index', as: :tag
  root 'welcome#index'

end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
  include Taggable

  has_many :taggings, as: :tagable
  has_many :tags, through: :taggings
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  # Load CanCan roles for Controller
  load_and_authorize_resource

  before_action :set_quotation, only: %i[show edit update destroy]

  # GET /quotations
  # GET /quotations.json
  def index
    @quotations = Quotation.all
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show; end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
  end

  # GET /quotations/1/edit
  def edit; end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)
    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'New quotation added!' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html do
          redirect_to @quotation,
                      notice: 'Quotation was successfully updated.'
        end
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy
    @quotation.destroy
    respond_to do |format|
      format.html { redirect_to quotations_url }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_quotation
    @quotation = Quotation.find(params[:id])
  end

  # Never trust parameters from the scary internet
  def quotation_params
    params.require(:quotation).permit(:title,
                                      :passage,
                                      :tag_list,
                                      :publish)
  end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_form.html.haml
= form_for @quotation do |f|
  - if @quotation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@quotation.errors.count, "error")} prohibited this quotation from being saved:"
      %ul
        - @quotation.errors.full_messages.each do |msg|
          %li= msg

  .field.stoic-dark-text
    = f.label :title
    = f.text_field :title
  .field.stoic-dark-text 
    = f.label :passage
    = f.text_area :passage, class: "form-control", rows: "4"
  .field
    = f.check_box :publish
    = f.label :publish_to_rehearsal_page
  .field
    = f.label :tag_list, "Category Tags"
    %br
    = f.label :tag_list, "(Separated by commas,"
    %br
    = f.label :tag_list, "e.g. Assent, Sex, Freedom) - Remember: always put the author tag FIRST as this will be displayed under source"
    = f.text_area :tag_list, class: "form-control", rows: "4"
  .actions
    = f.submit 'Save'

app/views/quotations/edit.html.haml
%h1 Editing Stoic Quotation

= render 'form'

= link_to 'Show', @quotation
\|
= link_to 'Back', quotations_path

app/views/quotations/index.html.haml
.container
  .row
    %h2.page-header Important Quotations from Stoic Philosophers
    %b Use these text passages from Stoic philosophers such as Seneca, Epictetus and the Roman Emperor and Stoic philosopher Marcus Aurelius (CE 121-180) to compare to your own daily thoughts and Stoic practice.
    %br
    %br
.container
  .row
    .panel.panel-primary
      %table.table.table-striped.table-responsive
        - @quotations.each do |quotation|
          %tr 
            %td= link_to truncate(quotation.title, length: 400), quotation, class: "panel panel-heading btn-group stoic-yellow", id: "quotation-label"
            %td= raw quotation.tags.map(&:name).map { |t| link_to t, tag_path(t), class: "btn btn-stoic-white" }.join('  ')
            - if can? :update, quotation
              %td= quotation.created_at.strftime("%d %b. %Y")
              %td= link_to 'Edit', edit_quotation_path(quotation)
              %td= link_to 'Destroy', quotation, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %br
      - if can? :update, @quotations
        = link_to 'New Quotation', new_quotation_path

app/views/quotations/new.html.haml
%h1 New quotation

= render 'form'

= link_to 'Back', quotations_path

app/views/quotations/show.html.haml
.container
  .row
    .col-md-8
      %p#notice= notice
      .card.bg-dark
        .card-header
          %h4= @quotation.title
        .card-body
          .card-text
            %h5= @quotation.passage + "\""
        .card-footer
          %h5
            Philosophical Category Tags:
          = raw @quotation.tags.map(&:name).map { |t| link_to t, tag_path(t), class: "small text-muted" }.join('  ')
        - if can? :update, @quotations
          = link_to 'Edit Quotation', edit_quotation_path(@quotation)