config/routes.rb
StoicPenknife::Application.routes.draw do
  devise_for :mailers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'my_devise/registrations' }

  resources :rehearsals
  resources :exercises
  resources :quotations
  resources :doctrines

  get 'index' => 'welcome#index'
  get 'about' => 'welcome#about'
  get 'how_it_works' => 'welcome#how_it_works'
  get 'contact' => 'welcome#contact'
  get 'doctrines_index' => 'doctrines#index'
  get 'doctrines_new' => 'doctrines#new'
  get 'doctrines_introduction' => 'doctrines#introduction'
  get 'doctrines_assent' => 'doctrines#assent'
  get 'doctrines_desire' => 'doctrines#desire'
  get 'doctrines_action' => 'doctrines#action'
  get 'doctrines_disciplines_intro' => 'doctrines#disciplines_intro'
  get 'doctrines_dogmas_intro' => 'doctrines#dogmas_intro'
  get 'users' => 'users#index'
  get 'tags/:tag', to: 'tags#index', as: :tag
  root 'welcome#index'

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  # Before actions are a great way to DRY out the Controller.
  # I don't need to set Exercise for show, edit, update and destroy
  # again and again. Each INSTANCE of the ExercisesController,
  # when it is generated by the application when an action is called,
  # then sets the @exercise instance variable for that action.
  # My "check_ownership" method, which Christoph helped me with,
  # is also a great way to set up a check (which, when connected with
  # before_action can get repeated across other action methods) to test,
  # in this case, to ensure that the exercise is either global or YOURS
  # if you are viewing, editing, updating or destroying it.
  # A simplification for this logic would be to have two controllers, one
  # as an Admin controller. Then you could separate controls rather than
  # the logic in check_ownership and all the logic in the CanCan Ability model.
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  before_action :set_exercise, only: %i[show edit update destroy]
  before_action :check_ownership, only: %i[edit update destroy]

  # Load CanCan roles for Controller
  load_and_authorize_resource

  # GET /exercises
  def index
    @global_exercises = Exercise.where(global: true)
                                .order(:updated_at).reverse
    # I added .try here as part of adding the feature to enable
    # non-logged-in users to access the exercises. it is a Rails
    # method but an anti-pattern to use it too much.
    # IF you need to use .try elsewhere, instead create a kind of
    # "custom nil object", aka a "Guest" User, who has
    # zero private exercises, a "name" of guest, etc.
    @exercises = Exercise.where(user_id: current_user.try(:id))
    @latest_exercise = if Exercise.where(global: true).count.positive?
                         Exercise.where(global: true).last
                       else
                         Exercise.new(global: true, title: 'Sample')
                       end
  end

  # GET /exercises/1
  def show
    @rehearsals = @exercise.rehearsals_for_user(current_user)
    exercise_tags = @exercise.tags
    @published_doctrines = Doctrine.where(publish: true)
                                   .find_me_with(exercise_tags)
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
    3.times do
      question = @exercise.questions.build
      question.answers.build
    end
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  def create
    @exercise = Exercise.new(exercise_params)
    @exercise.user_id = current_user.id
    if @exercise.save
      redirect_to @exercise, notice: 'Exercise was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /exercises/1
  def update
    # assign_attributes is ActiveModel method often used in update to
    # add the params as attributes to the model object without/before
    # saving them. Then you can have logic inbetween, for example in our
    # case to call the CanCan method authorize! to check whether this user
    # is authorized to update/change this model / database table
    @exercise.assign_attributes(exercise_params)

    block_private_user_global_editing

    if @exercise.save
      redirect_to @exercise, notice: 'Exercise was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /exercises/1
  def destroy
    @exercise.destroy

    redirect_to action: 'index'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  def check_ownership
    return if @exercise.user_id == current_user.id || @exercise.global?

    raise CanCan::AccessDenied.new(
      'You are not allowed to access this exercise, buddy!'
    )
  end

  def block_private_user_global_editing
    return if @exercise.user_id == current_user.id &&
              @exercise.global? == false ||
              current_user.admin? == true

    raise CanCan::AccessDenied.new(
      'You are not allowed to access this exercise, buddy!'
    )
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def exercise_params
    params.require(:exercise).permit(:_destroy,
                                     :title,
                                     :general_description,
                                     :category,
                                     :global,
                                     :buzzword,
                                     :tag_list,
                                     :icon,
                                     questions_attributes:
                                       %i[id inquiry _destroy])
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
  def randomize_color_css
    color_list = %w[
      primary
      danger
      info
      warning
      success
      dark
      secondary
    ]
    color_list.sample
  end

  def randomize_diagonal_css
    diagonal_css_list = %w[
      diagonal-up
      diagonal-down
    ]

    diagonal_css_list.sample
  end
end

app/views/exercises/_e_question_fields.html.haml
%p
.nested-fields
  .col-lg-8
    .input-group
      .input-group-btn
        = f.text_field :question, class: "form-control", id: "form-border", rows: "2"
        = f.hidden_field :id
        = link_to_remove_association "Remove Question", f, class: "btn btn-default"

app/views/exercises/_form.html.haml
= bootstrap_form_for(@exercise, label_errors: true) do |f|
  = f.hidden_field :user_id
  = f.text_field :title
  = f.text_area :general_description, rows: '4'
  = f.text_area :tag_list, label: 'Category Tags (Seperated by commas, e.g. Assent, Sex, Freedom)', class: 'form-control', rows: '4'
  = f.file_field :icon, label: 'Add an image icon', class: 'form-control'
  %h3 Think-Exercise Questions
  = f.fields_for :questions do |question|
    = render 'question_fields', f: question, id: 'question'
  .links
    = link_to_add_association 'Add New Question', f, :questions, class: 'btn btn-md btn-danger form-control mb-3'
  %h5 At least one question is required in order to create a new exercise.
  %h5 There is a limit of 7 questions per exercise.

  - if current_user.admin
    = f.check_box :global, class: 'checkbox', label: "Publish this exercise globally to all users of Stoic Penknife"
    %br
    = f.text_field :buzzword, label: 'Add an exciting buzzword-catchphrase for the exercise here', class: 'form-control'
  .actions
  %center
    = f.submit 'Save Exercise', class: 'btn btn-lg btn-danger'

:javascript
  $(document).ready(function() {
    // Make clear also on refresh that field is required. If field is empty, add is-invalid class. If field is now full (but ANOTHER field is empty) then make sure the filled-in field displays green/valid.
    if ($('textarea#exercise_general_description').val().length ==! 0){
      $('textarea#exercise_general_description').removeClass('is-invalid');
      $('textarea#exercise_general_description').addClass('is-valid');
    };
  });

  $(document).ready(function() {
    if ($('input#exercise_title').val().length ==! 0){
      $('input#exercise_title').removeClass('is-invalid');
      $('input#exercise_title').addClass('is-valid');
    };
  });
  
  // Change to green border is-valid bootstrap class once you type into the field
  $('#exercise_title').one('change',function () {
    $('#exercise_title').removeClass('is-invalid');
    $('#exercise_title').addClass('is-valid');
  });

  $('#exercise_general_description').one('change',function () {
    $('#exercise_general_description').removeClass('is-invalid');
    $('#exercise_general_description').addClass('is-valid');
  });

  // Hide Add Question Button (and check to re-add it) if more than 7 questions is reached
  $(document).ready(function() {
    $(function() {
      function check_to_hide_add_link() {
        if ($('.nested-fields:visible').length >= 6) {
          $('a.add_fields').hide();
        }
        else {
          $('a.add_fields').show();
        }
      }

      function check_to_re_add_add_link() {
        if ($('.nested-fields:visible').length = 6) {
          $('a.add_fields').show();
        }
      }

      $('.card-body').on('click', '.btn-md', function() {
        check_to_hide_add_link();
      });

      $('.card-body').on('click', '.btn-sm', function() {
        check_to_re_add_add_link();
      });
    });
  });

app/views/exercises/_question_fields.html.haml
.form-row.nested-fields
  .col
    = f.text_field :inquiry, hide_label: true, class: "form-control position-static", placeholder: "My Think-Exercise Question"
    = f.hidden_field :id
  .col-2
    = link_to_remove_association "Remove", f, class: "form-control btn btn-sm btn-danger"

app/views/exercises/edit.html.haml
.container
  .row
    .col-md-8
      .card.bg-dark
        .card-body
          .card-title
            %h1 Edit the exercise
          = render 'form'
          = link_to 'Back to List of Exercises', exercises_path, class: "btn btn-sm btn-info"

app/views/exercises/index.html.haml
.container-fluid
  .row.justify-content-center
    .col-10
      .card.bg-light
        .card-body
          %h2.text-dark Stoic Philosophical Think-Exercises
          %h4.text-dark
            Practice one of the
            %b.text-warning ancient techniques
            of the Stoic philosophers.
          %h6
            .card
              .card-header.bg-info
                Only you can read your own personal, private writing as you practice these exercises.
          .card-columns
            .card.bg-danger.mb-2.border-3.border-primary
              .banner-container.banner.border.border-primary.border-3.rounded
                %h5 Try this one first
              = link_to(image_tag(@latest_exercise.icon, alt: "Exercise Tag", class: "card-img-top", style: "width: 100%; height: 20vh; object-fit: cover"), @latest_exercise) if @latest_exercise.icon.attached?
              .card-body
                = link_to  @latest_exercise.title, @latest_exercise, class: "card-title btn btn-primary border border-light"
                .label{class: "border badge badge-pill badge-warning #{randomize_diagonal_css}"}
                  = @latest_exercise.buzzword
                %p{class: "card-text"}=truncate(@latest_exercise.general_description, length: 200)
              %p{class: "card-footer"}= raw @latest_exercise.tags.map(&:name).map { |t| link_to t, tag_path(t), class: "small text-light" }.join('  ')
            - @global_exercises.each do |global_exercise|
              .card{class: "bg-light"}
                = link_to(image_tag(global_exercise.icon, alt: "Exercise Tag", class: "card-img-top", style: "width: 100%; height: 20vh; object-fit: cover"), global_exercise) if global_exercise.icon.attached?
                .card-body
                  = link_to global_exercise.title, global_exercise, class: "card-title btn btn-danger border border-dark"
                  .label{class: "border badge badge-pill badge-#{randomize_color_css} #{randomize_diagonal_css}"}
                    = global_exercise.buzzword
                  %p{class: "card-text text-dark"}=truncate(global_exercise.general_description, length: 200)
                %p{class: "card-footer"}= raw global_exercise.tags.map(&:name).map { |t| link_to t, tag_path(t), class: "small text-primary" }.join('  ')
.container-fluid
  .row.justify-content-center.mt-3
    .col-10
      .card.bg-light.text-dark
        .card-body
          %h4
            Create and edit
            %b.text-warning your own
            custom exercises here.
          %h5 Here, both your custom exercise itself (your questions, etc.) and your personal writing as you practice the exercise, are private. Only you can read either of them.
          = link_to 'Create New Custom Exercise', new_exercise_path, class: "btn btn-danger mb-3"
          .card-columns
            - @exercises.each do |custom_exercise|
              .card
                = link_to(image_tag(custom_exercise.icon, alt: "Exercise Tag", class: "card-img-top", style: "width: 100%; height: 20vh; object-fit: cover")) if custom_exercise.icon.attached?
                .card-body
                  = link_to custom_exercise.title, custom_exercise, class: "card-title btn btn-outline-dark"
                  .label{class: "badge badge-pill badge-#{randomize_color_css} #{randomize_diagonal_css}"}
                    = custom_exercise.buzzword
                  %p{class: "card-text"}=truncate(custom_exercise.general_description, length: 200)
                  %p{class: "card-footer"}= raw custom_exercise.tags.map(&:name).map { |t| link_to t, tag_path(t), class: "small text-muted" }.join('  ')

app/views/exercises/new.html.haml
.container
  .row
    .col-md-8
      .card.bg-dark
        .card-body
          .card-title
            %h2 Create A New Exercise
          = render 'form'

app/views/exercises/show.html.haml
.container
  .row
    .col-md-7
      .card
        .card-body.bg-info
          %h3.card-title
            = @exercise.title
          = @exercise.general_description
          %p= raw @exercise.tags.map(&:name).map { |t| link_to t, tag_path(t), class: "small text-light" }.join('  ')
          = image_tag(@exercise.icon, alt: "Exercise Tag", class: "card-img-top", style: "width: 100%; height: 30vh; object-fit: cover") if @exercise.icon.attached?
    .col-md-4
      .row.mb-2
        - if @exercise.buzzword
          .label{class: "border badge badge-pill badge-#{randomize_color_css} #{randomize_diagonal_css} mb-2 mt-3"}
            = @exercise.buzzword
      .row.mb-2
        = link_to 'Practice It', new_rehearsal_path(:exercise => @exercise.id), class: "btn btn-lg btn-primary"
      .row.mb-2
        = link_to 'Back to Exercise List', exercises_path, class: "btn btn-sm btn-danger"
      .row.mb-2
      - if can? :update, @exercise
        .row.mb-2
          = link_to 'Edit', edit_exercise_path(@exercise), class: "btn btn-sm btn-danger mr-2"
          = link_to 'Delete', @exercise, method: :delete, data: { confirm: "Are you certain that you'd like to delete this philosophical exercise?" }, class: "btn btn-sm btn-danger"
      .row.mb-2
        - if @exercise.global == false
          .badge.badge-pill.badge-warning Your Custom Exercise
  - if @rehearsals.count > 0
    .row.mt-3
      .col-xl-12
        .card.bg-dark
          .card-body
            .card-title
              %h3 My Past Practice
            .table-responsive-xl
              %table.table.table-warning
                %tbody
                %th
                %th Day
                %th Place
                - @exercise.questions.each do |question|
                  %th= truncate(question.inquiry, length: 75)
                - @rehearsals.each do |rehearsal|
                  %tr{class: "bg-#{randomize_color_css} text-white"}
                    %td= link_to 'Read', rehearsal_path(rehearsal), class: "btn btn-sm btn-outline-light"
                    %td= rehearsal.created_at.strftime("%d.%m.%Y")
                    -if rehearsal.city?
                      %td= rehearsal.city
                    -else
                      %td Unknown City

                    - rehearsal.answers.each do |answer|
                      %td= truncate(answer.reply, length: 100)

  .row.mt-3
    .col-xl-12
      .card.bg-dark
        .card-header
          %h5 Steps in this Think-Exercise
        .card-body
          .card-columns
            - @exercise.questions.each_with_index do |question, count|
              .card.border-dark
                .card-body.text-dark
                  .card-title
                    %h5= "#{count+1}"
                  .card-text
                    = question.inquiry
  .row.mt-3
    .col-xl-12
      .card.bg-dark
        .card-body
          %h1.badge.badge-info Doctrines Pertaining to This Exercise
          - unless @published_doctrines.nil? || @published_doctrines.empty?
            - @published_doctrines.each do |doctrine|
              = render template: "doctrines/#{doctrine.file_name}"
          - else
            %p There are no Stoic philosophical doctrines associated with this exercise.